// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_dead : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean genRepairInput
        {
            get
            {
                return SteamVR_Actions.dead_genRepairInput;
            }
        }
        
        public virtual SteamVR_Action_Boolean GameObjectInteract
        {
            get
            {
                return SteamVR_Actions.dead_GameObjectInteract;
            }
        }
        
        public virtual SteamVR_Action_Boolean MovementForward
        {
            get
            {
                return SteamVR_Actions.dead_MovementForward;
            }
        }
        
        public virtual SteamVR_Action_Pose Movement
        {
            get
            {
                return SteamVR_Actions.dead_Movement;
            }
        }
    }
}
